import { PRODUCT_IMAGES } from "./assets";
import { OFFER_BANNER } from "./assets";

export const PRODUCTS = [
  {
    id: "1",
    time: "10 MINS",
    catogary: "Watches",
    catogaryImage: PRODUCT_IMAGES.WATCH_CATEGORY,
    productName: "Rolex 14 g",
    productImage: PRODUCT_IMAGES.WATCH1,
    quantity: "300 g",
    price: 2000,
    orderQuantity: 0,
  },
  {
    id: "2",
    time: "10 MINS",
    catogary: "Watches",
    catogaryImage: PRODUCT_IMAGES.WATCH_CATEGORY,
    productName: "G-Shock 1g",
    productImage: PRODUCT_IMAGES.WATCH2,
    quantity: "350 g",
    price: 2200,
    orderQuantity: 0,
  },
  {
    id: "3",
    time: "10 MINS",
    catogary: "Watches",
    catogaryImage: PRODUCT_IMAGES.WATCH_CATEGORY,
    productName: "Captain 14 generation",
    productImage: PRODUCT_IMAGES.WATCH3,
    quantity: "400 g",
    price: 1800,
    orderQuantity: 0,
  },
  {
    id: "4",
    time: "10 MINS",
    catogary: "Watches",
    catogaryImage: PRODUCT_IMAGES.WATCH_CATEGORY,
    productName: "Highland 13 pro",
    productImage: PRODUCT_IMAGES.WATCH4,
    quantity: "450 g",
    price: 2000,
    orderQuantity: 0,
  },
  {
    id: "5",
    time: "10 MINS",
    catogary: "Watches",
    catogaryImage: PRODUCT_IMAGES.WATCH_CATEGORY,
    productName: "Apple Watch 12 pro",
    productImage: PRODUCT_IMAGES.WATCH5,
    quantity: "460 g",
    price: 1000,
    orderQuantity: 0,
  },
  {
    id: "6",
    time: "10 MINS",
    catogary: "Watches",
    catogaryImage: PRODUCT_IMAGES.WATCH_CATEGORY,
    productName: "G-Shock 1g",
    productImage: PRODUCT_IMAGES.WATCH6,
    quantity: "500 g",
    price: 1440,
    orderQuantity: 0,
  },
  {
    id: "7",
    time: "10 MINS",
    catogary: "Watches",
    catogaryImage: PRODUCT_IMAGES.WATCH_CATEGORY,
    productName: "Captain 14 generation",
    productImage: PRODUCT_IMAGES.WATCH7,
    quantity: "1000 g",
    price: 1500,
    orderQuantity: 0,
  },
  {
    id: "8",
    time: "10 MINS",
    catogary: "Watches",
    catogaryImage: PRODUCT_IMAGES.WATCH_CATEGORY,
    productName: "Highland 13 pro",
    productImage: PRODUCT_IMAGES.WATCH8,
    quantity: "200 g",
    price: 3000,
    orderQuantity: 0,
  },
  {
    id: "9",
    time: "10 MINS",
    catogary: "Watches",
    catogaryImage: PRODUCT_IMAGES.WATCH_CATEGORY,
    productName: "Apple Watch 12 pro",
    productImage: PRODUCT_IMAGES.WATCH9,
    quantity: "1000 g",
    price: 4500,
    orderQuantity: 0,
  },
  {
    id: "10",
    time: "10 MINS",
    catogary: "Footwear",
    catogaryImage: PRODUCT_IMAGES.FOOTWEAR_CATEGORY,
    productName: "Flite pro",
    productImage: PRODUCT_IMAGES.FOOTWEAR1,
    quantity: "1380 g",
    price: 750,
    orderQuantity: 0,
  },
  {
    id: "11",
    time: "10 MINS",
    catogary: "Footwear",
    productName: "Sports Sega",
    catogaryImage: PRODUCT_IMAGES.FOOTWEAR_CATEGORY,
    productImage: PRODUCT_IMAGES.FOOTWEAR2,
    quantity: "1280 g",
    price: 600,
    orderQuantity: 0,
  },
  {
    id: "12",
    time: "10 MINS",
    catogary: "Footwear",
    productName: "Gold Star",
    catogaryImage: PRODUCT_IMAGES.FOOTWEAR_CATEGORY,
    productImage: PRODUCT_IMAGES.FOOTWEAR3,
    quantity: "310 g",
    price: 850,
    orderQuantity: 0,
  },
  {
    id: "13",
    time: "10 MINS",
    catogary: "Footwear",
    productName: "Nike pro",
    catogaryImage: PRODUCT_IMAGES.FOOTWEAR_CATEGORY,
    productImage: PRODUCT_IMAGES.FOOTWEAR4,
    quantity: "680 g",
    price: 900,
    orderQuantity: 0,
  },
  {
    id: "14",
    time: "10 MINS",
    catogary: "Footwear",
    productName: "Snikers",
    catogaryImage: PRODUCT_IMAGES.FOOTWEAR_CATEGORY,
    productImage: PRODUCT_IMAGES.FOOTWEAR5,
    quantity: "980 g",
    price: 1000,
    orderQuantity: 0,
  },
  {
    id: "15",
    time: "10 MINS",
    catogary: "Footwear",
    productName: "Nike pro",
    catogaryImage: PRODUCT_IMAGES.FOOTWEAR_CATEGORY,
    productImage: PRODUCT_IMAGES.FOOTWEAR6,
    quantity: "1080 g",
    price: 1440,
    orderQuantity: 0,
  },
  {
    id: "16",
    time: "10 MINS",
    catogary: "Footwear",
    productName: "Snikers",
    catogaryImage: PRODUCT_IMAGES.FOOTWEAR_CATEGORY,
    productImage: PRODUCT_IMAGES.FOOTWEAR7,
    quantity: "2000 g",
    price: 1500,
    orderQuantity: 0,
  },
  {
    id: "17",
    time: "10 MINS",
    catogary: "Clothing",
    productName: "Inner",
    catogaryImage: PRODUCT_IMAGES.CLOTHES_CATEGORY,
    productImage: PRODUCT_IMAGES.CLOTHES1,
    quantity: "2900 g",
    price: 750,
    orderQuantity: 0,
  },
  {
    id: "18",
    time: "10 MINS",
    catogary: "Clothing",
    productName: "Pant",
    catogaryImage: PRODUCT_IMAGES.CLOTHES_CATEGORY,
    productImage: PRODUCT_IMAGES.CLOTHES2,
    quantity: "200 g",
    price: 800,
    orderQuantity: 0,
  },
  {
    id: "19",
    time: "10 MINS",
    catogary: "Clothing",
    productName: "Shirt",
    catogaryImage: PRODUCT_IMAGES.CLOTHES_CATEGORY,
    productImage: PRODUCT_IMAGES.CLOTHES3,
    quantity: "1200 g",
    price: 850,
    orderQuantity: 0,
  },
  {
    id: "20",
    time: "10 MINS",
    catogary: "Clothing",
    productName: "Short Shirt",
    catogaryImage: PRODUCT_IMAGES.CLOTHES_CATEGORY,
    productImage: PRODUCT_IMAGES.CLOTHES4,
    quantity: "200 g",
    price: 700,
    orderQuantity: 0,
  },
  {
    id: "21",
    time: "10 MINS",
    catogary: "Clothing",
    productName: "Loar",
    catogaryImage: PRODUCT_IMAGES.CLOTHES_CATEGORY,
    productImage: PRODUCT_IMAGES.CLOTHES5,
    quantity: "1000 g",
    price: 900,
    orderQuantity: 0,
  },
  {
    id: "22",
    time: "10 MINS",
    catogary: "Clothing",
    productName: "Loar",
    catogaryImage: PRODUCT_IMAGES.CLOTHES_CATEGORY,
    productImage: PRODUCT_IMAGES.CLOTHES6,
    quantity: "200 g",
    price: 1000,
    orderQuantity: 0,
  },
  {
    id: "23",
    time: "10 MINS",
    catogary: "Bags & Wallets",
    productName: "American Trouist",
    catogaryImage: PRODUCT_IMAGES.BAGS_CATEGORY,
    productImage: PRODUCT_IMAGES.BAGS1,
    quantity: "300 g",
    price: 700,
    orderQuantity: 0,
  },
  {
    id: "24",
    time: "10 MINS",
    catogary: "Bags & Wallets",
    productName: "Tracking",
    catogaryImage: PRODUCT_IMAGES.BAGS_CATEGORY,
    productImage: PRODUCT_IMAGES.BAGS2,
    quantity: "500 g",
    price: 750,
    orderQuantity: 0,
  },
  {
    id: "25",
    time: "10 MINS",
    catogary: "Bags & Wallets",
    productName: "School",
    catogaryImage: PRODUCT_IMAGES.BAGS_CATEGORY,
    productImage: PRODUCT_IMAGES.BAGS3,
    quantity: "3100 g",
    price: 700,
    orderQuantity: 0,
  },
  {
    id: "26",
    time: "10 MINS",
    catogary: "Bags & Wallets",
    productName: "American Trouist",
    catogaryImage: PRODUCT_IMAGES.BAGS_CATEGORY,
    productImage: PRODUCT_IMAGES.BAGS4,
    quantity: "380 g",
    price: 700,
    orderQuantity: 0,
  },
  {
    id: "27",
    time: "10 MINS",
    catogary: "Bags & Wallets",
    productName: "Tracking",
    catogaryImage: PRODUCT_IMAGES.BAGS_CATEGORY,
    productImage: PRODUCT_IMAGES.BAGS5,
    quantity: "3801 g",
    price: 750800,
    orderQuantity: 0,
  },
  {
    id: "28",
    time: "10 MINS",
    catogary: "Bags & Wallets",
    productName: "School",
    catogaryImage: PRODUCT_IMAGES.BAGS_CATEGORY,
    productImage: PRODUCT_IMAGES.BAGS6,
    quantity: "3802 g",
    price: 1000,
    orderQuantity: 0,
  },
  {
    id: "51",
    time: "10 MINS",
    catogary: "Home Appliances",
    productName: "Air Conditioners",
    catogaryImage: PRODUCT_IMAGES.HOME_APP_CATEGORY,
    productImage: PRODUCT_IMAGES.HOME_APP1,
    quantity: "3803 g",
    price: 25000,
    orderQuantity: 0,
  },
  {
    id: "52",
    time: "10 MINS",
    catogary: "Home Appliances",
    productName: "Air Conditioners",
    catogaryImage: PRODUCT_IMAGES.HOME_APP_CATEGORY,
    productImage: PRODUCT_IMAGES.HOME_APP2,
    quantity: "3804 g",
    price: 30000,
    orderQuantity: 0,
  },
  {
    id: "53",
    time: "10 MINS",
    catogary: "Home Appliances",
    productName: "Refrigerators",
    catogaryImage: PRODUCT_IMAGES.HOME_APP_CATEGORY,
    productImage: PRODUCT_IMAGES.HOME_APP3,
    quantity: "3805 g",
    price: 12000,
    orderQuantity: 0,
  },
  {
    id: "54",
    time: "10 MINS",
    catogary: "Home Appliances",
    productName: "Refrigerators",
    catogaryImage: PRODUCT_IMAGES.HOME_APP_CATEGORY,
    productImage: PRODUCT_IMAGES.HOME_APP4,
    quantity: "3806 g",
    price: 15000,
    orderQuantity: 0,
  },
  {
    id: "55",
    time: "10 MINS",
    catogary: "Home Appliances",
    productName: "Microwaves",
    catogaryImage: PRODUCT_IMAGES.HOME_APP_CATEGORY,
    productImage: PRODUCT_IMAGES.HOME_APP5,
    quantity: "3807 g",
    price: 9000,
    orderQuantity: 0,
  },
  {
    id: "56",
    time: "10 MINS",
    catogary: "Home Appliances",
    productName: "Microwaves",
    catogaryImage: PRODUCT_IMAGES.HOME_APP_CATEGORY,
    productImage: PRODUCT_IMAGES.HOME_APP6,
    quantity: "3808 g",
    price: 7500,
    orderQuantity: 0,
  },
  {
    id: "57",
    time: "10 MINS",
    catogary: "Home Appliances",
    productName: "Washing Machine",
    catogaryImage: PRODUCT_IMAGES.HOME_APP_CATEGORY,
    productImage: PRODUCT_IMAGES.HOME_APP7,
    quantity: "3809 g",
    price: 18000,
    orderQuantity: 0,
  },
  {
    id: "58",
    time: "10 MINS",
    catogary: "Home Appliances",
    productName: "Washing Machine",
    catogaryImage: PRODUCT_IMAGES.HOME_APP_CATEGORY,
    productImage: PRODUCT_IMAGES.HOME_APP8,
    quantity: "4000 g",
    price: 18500,
    orderQuantity: 0,
  },
  {
    id: "59",
    time: "10 MINS",
    catogary: "Home Appliances",
    productName: "Chimney",
    catogaryImage: PRODUCT_IMAGES.HOME_APP_CATEGORY,
    productImage: PRODUCT_IMAGES.HOME_APP9,
    quantity: "3800 g",
    price: 24000,
    orderQuantity: 0,
  },
  {
    id: "60",
    time: "10 MINS",
    catogary: "Home Appliances",
    productName: "Chimney",
    catogaryImage: PRODUCT_IMAGES.HOME_APP_CATEGORY,
    productImage: PRODUCT_IMAGES.HOME_APP1,
    quantity: "3810 g",
    price: 14000,
    orderQuantity: 0,
  },
];

export const PROFILE_MENU = ["Profile", "Account", "Dashboard", "Logout"];

export const DILIVERY_CHARGES = 15;

export const CANCELLATION_PLOICY =
  "Orders cannot be cancelled once packed for delivery. In case of unexpected delays, a refund will be provided, if applicable.";

export const ISOFFER = true;

export const BANNERS = [
  OFFER_BANNER.OFFER1,
  OFFER_BANNER.OFFER2,
  OFFER_BANNER.OFFER3,
];
